### ISSUE TITLE
Banner stojący - projekt

### ISSUE THREAD

**Issue by grzegorzbartman** [DrupalCampWroclaw/organizacyjne_2015#14]
Może w tym roku bez daty i sponsorów? Tylko duże logo, tak ma Sesja Linuksowa. Wtedy można go używać w kolejnych latach.
Temat do dyskusji.

**Comment by grzegorzbartman** [comment]
Banner z poprzedniego roku

![image_001](https://cloud.githubusercontent.com/assets/1450802/7647758/8454dbc6-fada-11e4-8d2e-539bea20b1ba.png)

**Comment by grzegorzbartman** [comment]
Na czerwonym: www.drupalcamp.pl

Na miejscu sponsorów loga technologii
Drupal, PHP, JavaScript, AngularJS, MySQL, Jenskins CI, Apache, BACKBONE.JS, HTML5, CSS3, SASS, Bootstrap, PostreSQL, PHPUnit, Selenium

**Comment by car3oon** [comment]
![baner2015](https://cloud.githubusercontent.com/assets/4738588/7652674/357371a4-fb0f-11e4-9584-f7a6a3b099d9.jpg)

jak wszystko się zgadza to zrobię wersję z krzywymi.

**Comment by jaro2801** [comment]
zajebioza

2015-05-15 14:33 GMT+02:00 Łukasz Węgiel notifications@github.com:

**Comment by car3oon** [comment]
![baner2015n](https://cloud.githubusercontent.com/assets/4738588/7652966/3b15d946-fb12-11e4-9b45-fd0a0c42d271.jpg)

poprawione.

**Comment by car3oon** [comment]
https://drive.google.com/a/openbit.pl/file/d/0B3eXkxi4icFsN3BYSXNkaHlPS2c/view?usp=sharing
https://drive.google.com/a/openbit.pl/file/d/0B3eXkxi4icFsendRWHFkVUN2NzQ/view?usp=sharing

**Comment by grzegorzbartman** [comment]
Zamówione i zapłacone
