### ISSUE TITLE
Smycz - projekt

### ISSUE THREAD

**Issue by grzegorzbartman** [DrupalCampWroclaw/organizacyjne_2015#15]

**Comment by dinerrr** [comment]
![wersja 1](https://cloud.githubusercontent.com/assets/8255035/7626988/c2d62680-fa11-11e4-9da5-f290908e89ca.png)

![wersja 2](https://cloud.githubusercontent.com/assets/8255035/7626990/c9cedae0-fa11-11e4-9b64-4dc3e990c41f.png)

**Comment by grzegorzbartman** [comment]
![image_002](https://cloud.githubusercontent.com/assets/1450802/7648561/9922c4b4-fae4-11e4-8ca8-6a1429857acc.png)

**Comment by grzegorzbartman** [comment]
Zamówione i zapłacone
