### ISSUE TITLE
Ulotka z programem - projekt

### ISSUE THREAD

**Issue by grzegorzbartman** [DrupalCampWroclaw/organizacyjne_2015#26]
Projekt z poprzedniego roku https://github.com/DrupalCampWroclaw/organizacyjne/tree/master/ulotka

**Comment by car3oon** [comment]
![ulotka-2015-program1](https://cloud.githubusercontent.com/assets/4738588/7682114/e3e238e8-fd75-11e4-8d68-5d6b60d3dca2.jpg)
![ulotka-2015-program2](https://cloud.githubusercontent.com/assets/4738588/7682115/e3e3223a-fd75-11e4-9614-eef0a5f2d35e.jpg)

**Comment by grzegorzbartman** [comment]
Ze skype:

[17:13:05] Grzegorz Bartman: fajne :)
[17:13:16] Grzegorz Bartman: poprawki: w sobote party tez jest w hustawcw
[17:13:30] Grzegorz Bartman: sposnor graficzny -> sponsor grafiki
[17:14:13] Grzegorz Bartman: i moze calosc po angielsku, bo teraz jest ponglish troche
[17:14:42] Grzegorz Bartman: dni tygodnia na angielski i "program konferencji" na angielski, to bedzie chyba wszystko ok
[17:14:46] Grzegorz Bartman: a i nazwy sponsorow tez
[17:14:49] Grzegorz Bartman: typy sponsorow

**Comment by grzegorzbartman** [comment]
@car3oon jutro z rana wprowadz te poprawki

Wysłałem zapytanie o wycenę

**Comment by car3oon** [comment]
@grzegorzbartman poprawione
![ulotka-2015-program1](https://cloud.githubusercontent.com/assets/4738588/7721542/affbc972-fed8-11e4-9f99-83d5794ac2ab.jpg)
![ulotka-2015-program2](https://cloud.githubusercontent.com/assets/4738588/7721543/affc716a-fed8-11e4-9e8d-e51b8da3a7df.jpg)

wersja w krzywych i normalna do edycji poniżej:
https://drive.google.com/a/openbit.pl/file/d/0B3eXkxi4icFsREEzdnE2bzhfSWM/view?usp=sharing
https://drive.google.com/a/openbit.pl/file/d/0B3eXkxi4icFsUXA1ZFI5bWtvbEE/view?usp=sharing

**Comment by grzegorzbartman** [comment]
![zmiany](https://cloud.githubusercontent.com/assets/1450802/7724728/922f7544-fef4-11e4-89e4-dfc8a39bf349.jpg)

**Comment by car3oon** [comment]
![ulotka-2015-program2](https://cloud.githubusercontent.com/assets/4738588/7725099/d3815500-fef7-11e4-9491-5bafb891615e.jpg)

pliki: 
https://drive.google.com/a/openbit.pl/file/d/0B3eXkxi4icFsbjJhVmotSkg3cEE/view?usp=sharing
https://drive.google.com/a/openbit.pl/file/d/0B3eXkxi4icFsa1lYVHRZUWxfNU0/view?usp=sharing

**Comment by grzegorzbartman** [comment]
Zamówione
